// Renders the Nginx config for the built site from config.ini and prints it.
// scripts/manage.sh installs the output; nothing here needs root, so the config
// can be reviewed before it is written anywhere.
//
//   node scripts/nginx.js

import path from "node:path";
import { site } from "../src/lib/config.js";
import { distDir } from "../src/lib/paths.js";

const { port, nginxConf } = site.server;
// Map variables are global to the Nginx process; naming this one after the
// config file keeps it from colliding with another site on the same server.
const cacheVariable = `${path.basename(nginxConf, ".conf").replace(/[^a-z0-9]/gi, "_")}_cache`;

// The site ships no client-side JavaScript, so script-src can be closed outright;
// a JSON-LD block is data, not a script, and is not covered by it. Inline styles
// are unavoidable: KaTeX sizes every glyph with a style attribute, and the author
// writes them in Markdown. Images are allowed off-site so a linked illustration
// still loads. HSTS stays with Cloudflare, which is what terminates TLS.
const CSP = [
  "default-src 'none'",
  "script-src 'none'",
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data: https:",
  "font-src 'self'",
  "manifest-src 'self'",
  "base-uri 'none'",
  "form-action 'none'",
  "frame-ancestors 'self'",
].join("; ");

const wwwRedirect = site.host.includes(".") && !site.host.startsWith("www.")
  ? `
# www is not canonical: fold it onto the apex host so the two are never indexed
# as separate sites. TLS terminates upstream (Cloudflare), hence the literal https.
server {
  listen 127.0.0.1:${port};
  server_name www.${site.host};
  return 301 https://${site.host}$request_uri;
}
`
  : "";

console.log(`# Generated by scripts/nginx.js. Edit config.ini, not this file.

# Cache lifetime by path. Set through a map so the server block carries a single
# add_header: an add_header inside a location would drop the inherited ones.
map $uri $${cacheVariable} {
  default                "public, max-age=0, must-revalidate";
  ~^/static/_astro/      "public, max-age=31536000, immutable";
  ~^/static/tgpagella/   "public, max-age=31536000, immutable";
  ~^/static/             "public, max-age=2592000";
  ~^/favicon\\.ico$       "public, max-age=2592000";
}
${wwwRedirect}
server {
  listen 127.0.0.1:${port} default_server;
  server_name ${site.host};
  root ${distDir};
  index index.html;
  charset utf-8;

  # Path-only Location headers, so redirects keep the scheme the edge terminated on.
  absolute_redirect off;
  # Collapses //host into /host, so a redirect built from the path cannot become
  # the protocol-relative //host that a browser reads as another origin.
  merge_slashes on;
  # The version number tells an attacker which advisories to try.
  server_tokens off;

  add_header Cache-Control $${cacheVariable} always;
  add_header X-Content-Type-Options "nosniff" always;
  add_header Referrer-Policy "strict-origin-when-cross-origin" always;
  add_header X-Frame-Options "SAMEORIGIN" always;
  add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always;
  add_header Content-Security-Policy "${CSP}" always;

  gzip on;
  gzip_vary on;
  gzip_min_length 1024;
  gzip_types text/plain text/css text/xml application/xml application/javascript
             application/json application/manifest+json image/svg+xml;

  # One URL per page. Astro emits page.html (build.format "file"), so the .html
  # suffix and the trailing slash are both folded onto the canonical form.
  location = /index.html {
    return 301 /;
  }

  # The captured path may not contain a backslash (\\x5c, written as a code point so
  # it survives both this file and Nginx's own unescaping). Browsers follow the
  # WHATWG URL rules, where a backslash counts as a slash, so a Location of
  # /\\host/page resolves to https://host/page — an open redirect off this site. No
  # page here has one in its name, so such a request falls through to the 404 below.
  location ~ "^(/[^\\x5c]+)\\.html$" {
    return 301 $1$is_args$args;
  }

  location ~ "^(/[^\\x5c]+)/$" {
    return 301 $1$is_args$args;
  }

  # Reachable only through error_page, never as a URL of its own.
  location = /404.html {
    internal;
  }

  # Nothing published here is a dotfile. One that reaches dist/ — copied out of
  # public/ by accident — is not served. /.well-known stays reachable.
  location ~ "^/\\.(?!well-known/)" {
    return 404;
  }

  # This Nginx build ships no .webmanifest entry in mime.types, so the type is set
  # here. The block deliberately declares no add_header: one would replace, not
  # extend, the security headers inherited from the server.
  location = /site.webmanifest {
    default_type application/manifest+json;
  }

  location = / {
    try_files /index.html =404;
  }

  # =404 rather than a fallback to the home page: an unknown URL must not answer
  # 200 with the site's front page, which is what search engines read as a real page.
  location / {
    try_files $uri $uri.html =404;
  }

  error_page 404 /404.html;
}`);
