#!/usr/bin/env bash
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

usage() {
  cat <<USAGE
Usage: $(basename "$0") [options]

Options:
  --port <port>           Local port for Nginx (default: 1213)
  --server-name <name>    Nginx server_name (repeatable, default: _)
  --root <path>           Site root (default: dist/)
  --config-path <path>    Nginx config path (default: /etc/nginx/conf.d/md2html.conf)
  --skip-build            Skip npm run build
  --no-reload             Skip nginx reload
  --print-config          Print the generated config to stdout and exit
  -h, --help              Show this help
USAGE
}

require_cmd() {
  command -v "$1" >/dev/null || { echo "Missing command: $1"; exit 1; }
}

port="1213"
siteRoot="${DIR}/dist"
configPath="/etc/nginx/conf.d/md2html.conf"
skipBuild="0"
reloadNginx="1"
printConfig="0"
serverNames=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --port)
      port="$2"
      shift 2
      ;;
    --server-name)
      serverNames+=("$2")
      shift 2
      ;;
    --root)
      siteRoot="$2"
      shift 2
      ;;
    --config-path)
      configPath="$2"
      shift 2
      ;;
    --skip-build)
      skipBuild="1"
      shift
      ;;
    --no-reload)
      reloadNginx="0"
      shift
      ;;
    --print-config)
      printConfig="1"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1"
      usage
      exit 1
      ;;
  esac
done

if [[ "${#serverNames[@]}" -eq 0 ]]; then
  serverNames=("_")
fi

# --print-config renders the config without needing nginx, sudo, or a build, so it
# can be reviewed and syntax-checked before anything is installed.
if [[ "$printConfig" -eq 0 ]]; then
  require_cmd nginx
  require_cmd sudo

  if [[ "$skipBuild" -eq 0 ]]; then
    require_cmd npm
    pushd "$DIR" >/dev/null
    npm run build
    popd >/dev/null
  fi

  if command -v pm2 >/dev/null; then
    if pm2 describe md2html >/dev/null 2>&1; then
      pm2 delete md2html
    fi
  fi

  if [[ ! -d "$siteRoot" ]]; then
    echo "Site root not found: $siteRoot"
    exit 1
  fi
fi

# The first --server-name is the canonical host: it is the one the www variant
# redirects to. "_" means no public hostname was given (local serving), so no
# host-level redirect is emitted.
canonicalName="${serverNames[0]}"
wwwRedirect=""
if [[ "$canonicalName" != "_" && "$canonicalName" != www.* ]]; then
  wwwRedirect="$(cat <<WWW
# www is not canonical: fold it onto the apex host so the two are never indexed
# as separate sites. TLS terminates upstream (Cloudflare), hence the literal https.
server {
  listen 127.0.0.1:${port};
  server_name www.${canonicalName};
  return 301 https://${canonicalName}\$request_uri;
}

WWW
)"
  # Command substitution strips trailing newlines; restore the block separator.
  wwwRedirect+=$'\n\n'
fi

tmpConfig="$(mktemp)"
cat >"$tmpConfig" <<CONFIG
# Generated by scripts/setup-nginx.sh. Edit that script, not this file.

# Cache lifetime by path. Set through a map so the server block carries a single
# add_header: an add_header inside a location would drop the inherited ones.
map \$uri \$md2html_cache_control {
  default                     "public, max-age=0, must-revalidate";
  ~^/static/_astro/           "public, max-age=31536000, immutable";
  ~^/static/tgpagella/        "public, max-age=31536000, immutable";
  ~^/static/(css|js)/         "public, max-age=2592000";
  ~^/static/(img|og|icons)/   "public, max-age=2592000";
  ~^/favicon\.ico\$            "public, max-age=2592000";
}

${wwwRedirect}server {
  listen 127.0.0.1:${port} default_server;
  server_name ${serverNames[*]};
  root ${siteRoot};
  index index.html;
  charset utf-8;

  # Path-only Location headers, so redirects keep the scheme the edge terminated on.
  absolute_redirect off;

  add_header Cache-Control \$md2html_cache_control always;
  add_header X-Content-Type-Options "nosniff" always;
  add_header Referrer-Policy "strict-origin-when-cross-origin" always;
  add_header X-Frame-Options "SAMEORIGIN" always;
  add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always;

  gzip on;
  gzip_vary on;
  gzip_min_length 1024;
  gzip_types text/plain text/css text/xml application/xml application/javascript
             application/json application/manifest+json image/svg+xml;

  # One URL per page. Astro emits page.html (build.format "file"), so the .html
  # suffix and the trailing slash are both folded onto the canonical form.
  location = /index.html {
    return 301 /;
  }

  location ~ ^(/.+)\.html\$ {
    return 301 \$1\$is_args\$args;
  }

  location ~ ^(/.+)/\$ {
    return 301 \$1\$is_args\$args;
  }

  # Reachable only through error_page, never as a URL of its own.
  location = /404.html {
    internal;
  }

  # This nginx build ships no .webmanifest entry in mime.types, so the type is set
  # here. The block deliberately declares no add_header: one would replace, not
  # extend, the security headers inherited from the server.
  location = /site.webmanifest {
    default_type application/manifest+json;
  }

  location = / {
    try_files /index.html =404;
  }

  # =404 rather than a fallback to the home page: an unknown URL must not answer
  # 200 with the site's front page, which is what search engines read as a real page.
  location / {
    try_files \$uri \$uri.html =404;
  }

  error_page 404 /404.html;
}
CONFIG

if [[ "$printConfig" -eq 1 ]]; then
  cat "$tmpConfig"
  rm -f "$tmpConfig"
  exit 0
fi

configDir="$(dirname "$configPath")"
if [[ -w "$configDir" ]]; then
  mv "$tmpConfig" "$configPath"
else
  sudo mv "$tmpConfig" "$configPath"
fi

if ! sudo -v; then
  echo "Sudo authentication failed."
  exit 1
fi

nginxUser="$(awk '$1 == "user" { gsub(";", "", $2); print $2; exit }' /etc/nginx/nginx.conf 2>/dev/null || true)"
if [[ -z "$nginxUser" ]]; then
  nginxUser="www-data"
fi

parentDir="$siteRoot"
parentDirs=()
while [[ "$parentDir" != "/" && -n "$parentDir" ]]; do
  parentDirs+=("$parentDir")
  parentDir="$(dirname "$parentDir")"
done

if command -v setfacl >/dev/null; then
  sudo setfacl -m "u:${nginxUser}:rx" "${parentDirs[@]}"
  sudo setfacl -R -m "u:${nginxUser}:rX" "$siteRoot"
else
  sudo chmod o+rx "${parentDirs[@]}"
  sudo chmod -R o+rX "$siteRoot"
fi

if [[ -w /etc/nginx/nginx.conf ]]; then
  nginx -t
else
  sudo nginx -t
fi

if [[ "$reloadNginx" -eq 1 ]]; then
  if command -v systemctl >/dev/null; then
    sudo systemctl reload nginx || sudo systemctl restart nginx
  else
    sudo nginx -s reload
  fi
fi

echo "Nginx serving ${siteRoot} on 127.0.0.1:${port} (${configPath})."
